services:
  later:
    build: .
    container_name: later
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LATER_HTTP_LOG=0
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
